version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload:
          file: /target/site/jacoco/jacoco.xml
  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: install1
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: install2
          command: sudo apt-get update
      - run:
          name: install3
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build-docs
          command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "mouad.aguirar@alumni.univ-avignon.fr"
            git config user.name "iammouadagr"
      - add_ssh_keys:
          fingerprints:
            - "a0:87:20:42:35:be:78:49:b9:04:4d:f8:07:1e:06:5f"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs/

workflows:
  version: 2
  continuous-integration:
    jobs:
      - build-and-test
      - docs
      - docs-deploy:
          requires:
            - build-and-test
            - docs
          filters:
            branches:
              only: master

